# encoding:utf-8

import os

CURRENT_DIR = os.path.dirname(__file__).replace("\\", '/')
RESOURCE_DIR = CURRENT_DIR + "/ui/resource"


class Style():
    style_main = (
        "QMainWindow {\n"
        "    background: transparent;\n"
        "}\n"
        "QToolTip {\n"
        "    color: #ffffff;\n"
        "    background-color: rgba(27, 29, 35, 160);\n"
        "    border: 1px solid rgb(40, 40, 40);\n"
        "    border-radius: 2px;\n"
        "}\n"
        "/* LINE EDIT */\n"
        "QLineEdit {\n"
        "    background-color: rgb(25, 25, 25);\n"
        "    border-radius: 5px;\n"
        "    border: 2px solid rgb(25, 25, 25);\n"
        "    padding-left: 10px;\n"
        "}\n"
        "QLineEdit:hover {\n"
        "    border: 2px solid rgb(64, 71, 88);\n"
        "}\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid rgb(91, 101, 124);\n"
        "}\n"
        "\n"
        "/* SCROLL BARS */\n"
        "QScrollBar:horizontal {\n"
        "    border: none;\n"
        "    background: rgb(56, 56, 56);\n"
        "    height: 14px;\n"
        "    margin: 0px 21px 0 21px;\n"
        "    border-radius: 0px;\n"
        "}\n"
        "QScrollBar::handle:horizontal {\n"
        "    background: rgb(85, 170, 255);\n"
        "    min-width: 25px;\n"
        "    border-radius: 7px\n"
        "}\n"
        "QScrollBar::add-line:horizontal {\n"
        "    border: none;\n"
        "    background: rgb(55, 63, 77);\n"
        "    width: 20px;\n"
        "    border-top-right-radius: 7px;\n"
        "    border-bottom-right-radius: 7px;\n"
        "    subcontrol-position: right;\n"
        "    subcontrol-origin: margin;\n"
        "}\n"
        "QScrollBar::sub-line:horizontal {\n"
        "    border: none;\n"
        "    background: rgb(55, 63, 77);\n"
        "    width: 20px;\n"
        "    border-top-left-radius: 7px;\n"
        "    border-bottom-left-radius: 7px;\n"
        "    subcontrol-position: left;\n"
        "    subcontrol-origin: margin;\n"
        "}\n"
        "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
        "{\n"
        "     background: none;\n"
        "}\n"
        "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
        "{\n"
        "     background: none;\n"
        "}\n"
        " QScrollBar:vertical {\n"
        "    border: none;\n"
        "    background: rgb(56, 56, 56);\n"
        "    width: 14px;\n"
        "    margin: 21px 0 21px 0;\n"
        "    border-radius: 0px;\n"
        " }\n"
        " QScrollBar::handle:vertical {    \n"
        "    background: rgb(85, 170, 255);\n"
        "    min-height: 25px;\n"
        "    border-radius: 7px\n"
        " }\n"
        " QScrollBar::add-line:vertical {\n"
        "     border: none;\n"
        "    background: rgb(55, 63, 77);\n"
        "     height: 20px;\n"
        "    border-bottom-left-radius: 7px;\n"
        "    border-bottom-right-radius: 7px;\n"
        "     subcontrol-position: bottom;\n"
        "     subcontrol-origin: margin;\n"
        " }\n"
        " QScrollBar::sub-line:vertical {\n"
        "    border: none;\n"
        "    background: rgb(55, 63, 77);\n"
        "     height: 20px;\n"
        "    border-top-left-radius: 7px;\n"
        "    border-top-right-radius: 7px;\n"
        "     subcontrol-position: top;\n"
        "     subcontrol-origin: margin;\n"
        " }\n"
        " QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
        "     background: none;\n"
        " }\n"
        "\n"
        " QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
        "     background: none;\n"
        " }\n"
        "\n"
        "/* CHECKBOX */\n"
        "QCheckBox::indicator {\n"
        "    border: 3px solid rgb(56, 56, 56);\n"
        "    width: 15px;\n"
        "    height: 15px;\n"
        "    border-radius: 10px;\n"
        "    background: rgb(44, 49, 60);\n"
        "}\n"
        "QCheckBox::indicator:hover {\n"
        "    border: 3px solid rgb(58, 66, 81);\n"
        "}\n"
        "QCheckBox::indicator:checked {\n"
        "    background: 3px solid rgb(56, 56, 56);\n"
        "    border: 3px solid rgb(56, 56, 56);    \n"
        f"    background-image: url({RESOURCE_DIR}/icons/16x16/cil-check-alt.png);\n"
        "}\n"
        "\n"
        "/* RADIO BUTTON */\n"
        "QRadioButton::indicator {\n"
        "    border: 3px solid rgb(56, 56, 56);\n"
        "    width: 15px;\n"
        "    height: 15px;\n"
        "    border-radius: 10px;\n"
        "    background: rgb(44, 49, 60);\n"
        "}\n"
        "QRadioButton::indicator:hover {\n"
        "    border: 3px solid rgb(58, 66, 81);\n"
        "}\n"
        "QRadioButton::indicator:checked {\n"
        "    background: 3px solid rgb(94, 106, 130);\n"
        "    border: 3px solid rgb(56, 56, 56);    \n"
        "}\n"
        "\n"
    )
    style_bt_standard = (
        "QPushButton {\n"
        "    background-image: ICON_REPLACE;\n"
        "    background-position: left center;\n"
        "    background-repeat: no-repeat;\n"
        "    border: none;\n"
        "    border-left: 28px solid rgb(25, 25, 25);\n"
        "    background-color: rgb(27, 29, 35);\n"
        "    text-align: left;\n"
        "    padding-left: 45px;\n"
        "}\n"
        "QPushButton[Active=true] {\n"
        "    background-image: ICON_REPLACE;\n"
        "    background-position: left center;\n"
        "    background-repeat: no-repeat;\n"
        "    border: none;\n"
        "    border-left: 28px solid rgb(27, 29, 35);\n"
        "    border-right: 5px solid rgb(44, 49, 60);\n"
        "    background-color: rgb(27, 29, 35);\n"
        "    text-align: left;\n"
        "    padding-left: 45px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "    background-color: rgb(33, 37, 43);\n"
        "    border-left: 28px solid rgb(33, 37, 43);\n"
        "}\n"
        "QPushButton:pressed {\n"
        "    background-color: rgb(85, 170, 255);\n"
        "    border-left: 28px solid rgb(85, 170, 255);\n"
        "}\n"
        "\n"
    )
